# Generated by Django 5.0.4 on 2024-04-22 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='model_name',
            new_name='award_name',
        ),
    ]
