# Generated by Django 5.0.4 on 2024-04-22 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_alter_subject_subject_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject_score',
        ),
    ]
