# Generated by Django 5.0.4 on 2024-04-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0004_remove_subject_subject_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='question_no',
            field=models.IntegerField(default=None),
        ),
    ]
